import { TProduct } from "@/types/product-t";

export const initialProducts: TProduct[] = [
  {
    _id: "test",
    sku: "test",
    color: 0,
    cost: 0,
    name: "Avocadoes",
    price: 3.2,
    shape: "test",
    soldBy: "test",
    avatar: "test",
    seller: "test",
    company: "test",
    category: "test",
    barcode: "test",
    modifiers: [],
    isForSale: true,
    syncOnline: true,
    trackStock: true,
    stockQuantity: 0,
    compositeItems: [],
    useProduction: true,
    isCompositeItem: true,
    lowStockThreshold: 0,
  },
  {
    _id: "test",
    sku: "test",
    color: 0,
    cost: 0,
    name: "test",
    price: 0,
    shape: "test",
    soldBy: "test",
    avatar: "test",
    seller: "test",
    company: "test",
    category: "test",
    barcode: "test",
    modifiers: [],
    isForSale: true,
    syncOnline: true,
    trackStock: true,
    stockQuantity: 0,
    compositeItems: [],
    useProduction: true,
    isCompositeItem: true,
    lowStockThreshold: 0,
  },
  {
    _id: "test",
    sku: "test",
    color: 0,
    cost: 0,
    name: "test",
    price: 0,
    shape: "test",
    soldBy: "test",
    avatar: "test",
    seller: "test",
    company: "test",
    category: "test",
    barcode: "test",
    modifiers: [],
    isForSale: true,
    syncOnline: true,
    trackStock: true,
    stockQuantity: 0,
    compositeItems: [],
    useProduction: true,
    isCompositeItem: true,
    lowStockThreshold: 0,
  },
  {
    _id: "test",
    sku: "test",
    color: 0,
    cost: 0,
    name: "test",
    price: 0,
    shape: "test",
    soldBy: "test",
    avatar: "test",
    seller: "test",
    company: "test",
    category: "test",
    barcode: "test",
    modifiers: [],
    isForSale: true,
    syncOnline: true,
    trackStock: true,
    stockQuantity: 0,
    compositeItems: [],
    useProduction: true,
    isCompositeItem: true,
    lowStockThreshold: 0,
  },
];
