export type TUser = {
  till: number;
  role: string;
  pin?: string;
  phone: string;
  email: string;
  country: string;
  pincode: string;
  fullName: string;
  company: string;
  password: string;
  companies: string[];
  companyName: string;
  pinnedInput: boolean;
  baseCurrence: string;
  permissions: string[];
  receitsCount: number;
  subscriptions: string[];
  paynowActivated: boolean;
  _id: string | null | undefined;
};
